[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/rakyll/hey"
  branch = "custom_output_formatter"
  source = "github.com/kpacha/hey"

[prune]
  go-tests = true
  unused-packages = true
